# Generated by Django 5.0.6 on 2024-09-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Где необходимо выполнять привычку', max_length=160, verbose_name='Место')),
                ('time', models.DateTimeField(help_text='Когда необходимо выполнять привычку', verbose_name='Время')),
                ('action', models.CharField(help_text='Действие представляющее привычку', max_length=160, verbose_name='Действие')),
                ('is_nice_habit', models.BooleanField(default=True, help_text='Приятная привычка', verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('1', 'Ежедневно'), ('2', 'Раз в 2 дня'), ('3', 'Раз в 3 дня'), ('4', 'Раз в 4 дня'), ('5', 'Раз в 5 дней'), ('6', 'Раз в 6 дней'), ('7', 'Раз в 7 дней')], default='1', help_text='Напоминание о выполнении привычки', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение после выполнения привычки', max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration_time', models.PositiveIntegerField(default=120, help_text='Необходимое время пользователю на выполнение привычки', verbose_name='Время на выполнение (сек)')),
                ('is_published', models.BooleanField(default=True, help_text='Публичный доступ для других пользователей', verbose_name='Признак публичности привычки')),
                ('next_date', models.DateField(blank=True, help_text='Выполнить привычку в этот день', null=True, verbose_name='Дата следующего выполнения привычки')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привычка, которая связана с другой привычкой, указывается для полезной', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, help_text='Создатель привычки', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
